packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.7.3
  '@antfu/ni': ^0.23.0
  '@antfu/utils': ^0.7.10
  '@iconify-json/carbon': ^1.2.1
  '@iconify-json/svg-spinners': ^1.2.0
  '@shikijs/core': ^1.20.0
  '@types/adm-zip': ^0.5.5
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/json-stable-stringify': ^1.0.36
  '@types/node': ^22.7.3
  '@types/semver': ^7.5.8
  '@unocss/eslint-config': ^0.62.4
  '@unocss/eslint-plugin': ^0.62.4
  '@unocss/reset': ^0.62.4
  '@vitejs/plugin-vue': ^5.1.4
  '@vitest/expect': ^2.1.1
  '@vue-macros/volar': ^0.30.2
  '@vueuse/core': ^11.1.0
  adm-zip: ^0.5.16
  bumpp: ^9.5.2
  chai: ^5.1.1
  chalk: ^5.3.0
  cson: ^8.4.0
  dotenv: ^16.4.5
  eslint: ^9.11.1
  esno: ^4.7.0
  fast-glob: ^3.3.2
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.1.1
  jsonc-parser: ^3.3.1
  lint-staged: ^15.2.10
  octokit: ^4.0.2
  ofetch: ^1.4.0
  oniguruma-to-js: ^0.4.3
  p-limit: ^6.1.0
  pnpm: ^9.11.0
  rimraf: ^6.0.1
  semver: ^7.6.3
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.6.2
  unbuild: ^2.0.0
  unocss: ^0.62.4
  unplugin-auto-import: ^0.18.3
  unplugin-vue-components: ^0.27.4
  unplugin-vue-macros: ^2.12.2
  unplugin-vue-router: ^0.10.8
  vite: ^5.4.8
  vitest: ^2.1.1
  vue: ^3.5.9
  vue-router: ^4.4.5
  vue-tsc: ^2.1.6
  yaml: ^2.5.1
