packages:
  - playground
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@antfu/ni': ^0.23.1
  '@antfu/utils': ^0.7.10
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/svg-spinners': ^1.2.1
  '@shikijs/core': ^1.24.2
  '@types/adm-zip': ^0.5.7
  '@types/cson': ^7.20.3
  '@types/js-yaml': ^4.0.9
  '@types/json-stable-stringify': ^1.1.0
  '@types/node': ^22.10.2
  '@types/semver': ^7.5.8
  '@unocss/eslint-config': ^0.65.1
  '@unocss/eslint-plugin': ^0.65.1
  '@unocss/reset': ^0.65.1
  '@vitejs/plugin-vue': ^5.2.1
  '@vitest/expect': ^2.1.8
  '@vue-macros/volar': ^0.30.8
  '@vueuse/core': ^12.0.0
  adm-zip: ^0.5.16
  bumpp: ^9.9.1
  chai: ^5.1.2
  chalk: ^5.3.0
  cson: ^8.4.0
  dotenv: ^16.4.7
  eslint: ^9.17.0
  esno: ^4.8.0
  fast-glob: ^3.3.2
  fast-plist: ^0.1.3
  js-yaml: ^4.1.0
  json-stable-stringify: ^1.1.1
  jsonc-parser: ^3.3.1
  lint-staged: ^15.2.11
  octokit: ^4.0.2
  ofetch: ^1.4.1
  oniguruma-to-js: ^0.4.3
  p-limit: ^6.1.0
  pnpm: ^9.15.0
  rimraf: ^6.0.1
  semver: ^7.6.3
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  typescript: ^5.7.2
  unbuild: ^3.0.1
  unocss: ^0.65.1
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.27.5
  unplugin-vue-macros: ^2.13.6
  unplugin-vue-router: ^0.10.9
  vite: ^6.0.3
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.1.10
  yaml: ^2.6.1
